### ISSUE TITLE
Trying to compile our Lava network protobufs. 

### ISSUE THREAD

**Issue by ranlavanet** [cosmology-tech/telescope#359]
getting this error: 
```
/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/utils.js:294
    throw new Error('instanceType() cannot find protobufjs Type');
          ^

Error: instanceType() cannot find protobufjs Type
    at instanceType (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/utils.js:294:11)
    at /usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:291:45
    at Array.reduce (<anonymous>)
    at traverseFields (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:227:34)
    at traverseType (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:425:13)
    at recursiveTraversal (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:533:12)
    at Object.keys.reduce.type (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:560:25)
    at Array.reduce (<anonymous>)
    at recursiveTraversal (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:559:38)
    at Object.keys.reduce.type (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:560:25)
```
Node.js v18.12.1

**Comment by Zetazzz** [comment]
Hi, Thx for the feedback.

The error was thrown by this:
    if (obj.name.match(/^[a-z]/)) {
        throw new Error('instanceType() cannot find protobufjs Type')
    }
For a type, we consider that it shouldn't start with a lowercase letter.
So please check if there's any type starts with a lowercase letter.
Thank you very much!

**Comment by pyramation** [comment]
closing this, @ranlavanet if you have a reproduceable example, let us know and reopen and issue
