### ISSUE TITLE
Invalid string format. Only non-negative integers in decimal representation supported.

### ISSUE THREAD

**Issue by Wgil** [cosmology-tech/telescope#642]
Dear Telescope team,

I have the following definition in a proto file:

```proto
message QueryOpenEstResponse {
  string weight_balance_ratio = 2 [
    (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec",
    (gogoproto.nullable) = false
  ];
}
```

The issue that I'm having is that such field can be a negative number as it's allowed in CosmosSDK but since it's decoded using Decimal.fromAtomics after running `yarn codegen`:

```js
case 2:
          message.weightBalanceRatio = Decimal.fromAtomics(reader.string(), 18).toString();
```

I get an error trying to decode its value:
```
Error: Invalid string format. Only non-negative integers in decimal representation supported.
    at new Decimal (decimal.js:103:1)
    at Decimal.fromAtomics (decimal.js:59:1)
    at Object.decode (query.ts:2215:48)
    at eval (query.rpc.Query.ts:119:54)
```

I tried removing the custom `types.Dec` to decode it as a string but my number gets decoded wrongly.

Do you guys have any alternative for this?
Thank you

**Comment by Zetazzz** [comment]
Hi, this is the problem that the Decimal implemented in cosmjs doesn't support the negative. 
Is it ok for this field to use int64? it will be Bigint in generated ts code

**Comment by Wgil** [comment]
Hi @Zetazzz ,

How would it convert it to decimal then? Maybe it's better if it would be a string in the generated ts code that includes the decimal part already.

Thanks for the interest on supporting this

**Comment by KeKs0r** [comment]
@Wgil  Was there ever a solution to this problem? I am trying to generate decoders that run into this issue.

**Comment by webmaster128** [comment]
There seems to be a long history of tweeking the decimal type to make it work for Agoric and the Cosmos SDK Dec type. Looking at https://github.com/hyperweb-io/telescope/blob/0e4847cf8facfbbc8c35f55996925871bfcf4312/packages/telescope/src/helpers/decimals.ts we see a fork of CosmJS' Decimal class. It should not be too hard to make it support negative numbers without touching CosmJS. I think this change makes sense as Telescope's fork is explicitly designed to handle Cosmos SDK decimals.
